# Generated by Django 5.0 on 2024-01-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carsshop", "0003_order_invoice_url_order_order_id_order_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonoSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_key", models.CharField(max_length=100, unique=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
