# Generated by Django 5.0 on 2024-01-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carsshop", "0004_monosettings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MonoSettings",
        ),
    ]
