# Generated by Django 5.0 on 2024-02-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carsshop", "0005_delete_monosettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderquantity",
            name="order",
        ),
        migrations.AddField(
            model_name="order",
            name="car_types",
            field=models.ManyToManyField(to="carsshop.orderquantity"),
        ),
    ]
