name: Black Format

on:
  push:
    branches:
      - main  # Adjust the branch as needed
jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace '3.x' with your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black

    - name: Run Black
      run: black .
